### ISSUE TITLE
Question: recommended resource requirements

### ISSUE THREAD

**Issue by m-idler** [nymanjens/quizmaster#7]
Hello,
actually not really an issue...
Do you already have any experience about the performance, especially recommendations for cpu / ram / bandwidth for e.g. 5, 10, 25, 50 users?
thank you

**Comment by nymanjens** [comment]
I run mine on a cheap VPS with 1GB of RAM memory (and the other specs are along the same line) and I've been able to accomodate 13 users without seeing any scale-related issues.

The server does need a stable internet connection though, because it jars the experience if the websockets get broken (even though I try to set them up again after breaking, that system doesn't seem to work that well)
